# Use .NET 10.0 to match your scaffolded project
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
#COPY *.csproj ./
COPY ["MyAiApi/MyAiApi.csproj", "MyAiApi/"]
COPY ["DataInjestion/*.csproj", "DataInjestion/"]
RUN dotnet restore MyAiApi/MyAiApi.csproj
COPY . .
RUN dotnet publish -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app/out .
EXPOSE 8080
ENTRYPOINT ["dotnet", "MyAiApi.dll"]